name: publish 🚀

on:
  workflow_dispatch:
  push:
    branches : 
    - master

jobs:
  publish : 
    runs-on : ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version : '6.0.x'
          
      - name: Restore
        run: dotnet restore ./WT.WebFlexFramework/WT.WebFlexFramework.sln
        
      - name: Build
        run: dotnet build ./WT.WebFlexFramework/WT.WebFlexFramework.sln  --configuration Release --no-restore
        
      - name: Publish
        run : dotnet publish ./WT.WebFlexFramework/WT.WebFlexFramework.sln  --configuration Release --no-build 
        
      
