name: publish 🚀

on:
  workflow_dispatch:
  push:
    branches : 
    - master

env:
  AZURE_WEBAPP_NAME : wtwebapp
  AZUR_WEBAPP_PACKAGE_PATH: '/home/runner/work/WT.WebFlexFramework/WT.WebFlexFramework/WT.WebFlexFramework/WT.WebApplication/bin/Release/net6.0/publish/' 


jobs:
  publish : 
    runs-on : ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version : '6.0.x'
          
      - name: Restore
        run: dotnet restore ./WT.WebFlexFramework/WT.WebFlexFramework.sln
        
      - name: Build
        run: dotnet build ./WT.WebFlexFramework/WT.WebFlexFramework.sln  --configuration Release --no-restore
        
      - name: Publish
        run : dotnet publish ./WT.WebFlexFramework/WT.WebFlexFramework.sln  --configuration Release --no-build --property:PackageOutputPath='${{env.AZUR_WEBAPP_PACKAGE_PATH}}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZUR_WEBAPP_PACKAGE_PATH}}"
